INSERT INTO CATEGORY (NAME,DESCRIPTION) values ('CATEGORIA 1','DESC 1'); 
INSERT INTO CATEGORY (NAME,DESCRIPTION) values ('CATEGORIA 2','DESC 2'); 
INSERT INTO CATEGORY (NAME,DESCRIPTION) values ('CATEGORIA 3','DESC 3'); 
INSERT INTO CATEGORY (NAME,DESCRIPTION) values ('CATEGORIA 4','DESC 4'); 
INSERT INTO CATEGORY (NAME,DESCRIPTION) values ('CATEGORIA 5','DESC 5'); 
INSERT INTO FARM (address,extension,category_id,name,description) values ('DIRECCION 1',1,1,'HACIENDA 1','DESC 1'); 
INSERT INTO FARM (address,extension,category_id,name,description) values ('DIRECCION 2',2,1,'HACIENDA 2','DESC 2'); 
INSERT INTO FARM (address,extension,category_id,name,description) values ('DIRECCION 3',3,2,'HACIENDA 3','DESC 3'); 
INSERT INTO FARM (address,extension,category_id,name,description) values ('DIRECCION 4',4,2,'HACIENDA 4','DESC 4');  
INSERT INTO FARM (address,extension,category_id,name,description) values ('DIRECCION 5',5,2,'HACIENDA 5','DESC 5');  
INSERT INTO FARM (address,extension,category_id,name,description) values ('DIRECCION 6',6,3,'HACIENDA 6','DESC 6'); 
INSERT INTO FARM (address,extension,category_id,name,description) values ('DIRECCION 7',7,3,'HACIENDA 7','DESC 7'); 
INSERT INTO FARM (address,extension,category_id,name,description) values ('DIRECCION 8',8,4,'HACIENDA 8','DESC 8'); 
INSERT INTO FARM (address,extension,category_id,name,description) values ('DIRECCION 9',9,5,'HACIENDA 9','DESC 9'); 
INSERT INTO FARM (address,extension,category_id,name,description) values ('DIRECCION 10',10,5,'HACIENDA 10','DESC 10');
INSERT INTO client (age,email,name,password) VALUES(41,'sandrajohannaduran@hotmail.com','SANDRA JOHANNA DURAN CHACON','37861963');
INSERT INTO client (age,email,name,password) VALUES(43,'taniheg104@xhyemail.com','JESUS ERNESTO LOPEZ TELLEZ','13563084');
INSERT INTO client (age,email,name,password) VALUES(44,'luisa.lievano98@gmail.com','CESAR AUGUSTO LIEVANO ','79763896');
INSERT INTO client (age,email,name,password) VALUES(26,'lizeth86@gmail.com','LIZETH YURANY PABON PARRA','1026587153');
INSERT INTO client (age,email,name,password) VALUES(22,'lady.perez-p@uniminuto.edu.co','LADY ESMERALDA PEREZ PEREZ','1002462429');
INSERT INTO client (age,email,name,password) VALUES(29,'JFFORERO59@GMAIL.COM','YEFERSON STIVEN FORERO ARDILA','1022988145');
INSERT INTO client (age,email,name,password) VALUES(50,'mariaplazas43@gmail.com','MARIA YAKELINE PLAZAS GRANADOS','52039543');
INSERT INTO client (age,email,name,password) VALUES(29,'pedroantoniocardenas792@gmail.com','PEDRO ANTONIO CARDENAS BRIÑEZ','1105684792');
INSERT INTO client (age,email,name,password) VALUES(21,'aleja1207mfc@gmail.com','MARIA ALEJANDRA MURILLO ORTIZ','1001096426');
INSERT INTO client (age,email,name,password) VALUES(27,'julianc.ramirez.valenzuela@gmail.com','JULIAN CAMILO RAMIREZ VALENZUELA','1107089742');
INSERT INTO client (age,email,name,password) VALUES(33,'NATALIACUADROG@GMAIL.COM','NEIDY NATHALIA CUADRADO GARCIA','1054091696');
INSERT INTO client (age,email,name,password) VALUES(30,'alopezgonzalez1@gmail.com','CAMILO ANDRES GONZALEZ LOPEZ','1052399367');
INSERT INTO client (age,email,name,password) VALUES(28,'erica78978@hotmail.com','ERICA LORENA VALDERRAMA CONTRERAS','1073168285');
INSERT INTO client (age,email,name,password) VALUES(21,'yesicasanta54@gmail.com','YESICA YULIANA SANTA QUESADA','1006149751');
INSERT INTO client (age,email,name,password) VALUES(26,'yessicapayoma@misena.edu.co','YESSICA FERNANDA PAYOMA CARVAJAL','1082216428');
INSERT INTO client (age,email,name,password) VALUES(58,'JUANKLOM64@HOTMAIL.COM','JUAN CARLOS LOZANO MEDINA','12126551');
INSERT INTO client (age,email,name,password) VALUES(22,'dvfer1692@gmail.com','YULY FERNANDA DUQUE VALDES','1007204081');
INSERT INTO client (age,email,name,password) VALUES(41,'lilikheme@gmail.com','LILI SORAIDA BECERRA MEDINA','46453427');
INSERT INTO client (age,email,name,password) VALUES(26,'josegalvis@gmail.com','JOSE ALEXANDER GALVIS CONTRERAS','1098826926');
INSERT INTO client (age,email,name,password) VALUES(21,'CROZOFELIPE96@GMAIL.COM','ARNOLD ROSO OSPINA','1000124182');
INSERT INTO client (age,email,name,password) VALUES(21,'camilosada15@gmail.com','JUAN CAMILO LOSADA LOPEZ','1001046376');
INSERT INTO client (age,email,name,password) VALUES(21,'brayannicolaycalderongordillo@gmail.com','BRAYAN NICOLAY CALDERON GORDILLO','1000003630');
INSERT INTO client (age,email,name,password) VALUES(27,'belinda066@hotmail.com','BELINDA MARIANA FERNANDEZ PALACIO','1124031869');
INSERT INTO client (age,email,name,password) VALUES(38,'arto0590@hotmail.co','MARIO HUMBERTO MIRANDA MORENO','13275539');
INSERT INTO client (age,email,name,password) VALUES(34,'camilarqm@gmail.com','CAMILA ANDREA RODRIGUEZ QUINCHANEGUA','1022349375');
INSERT INTO client (age,email,name,password) VALUES(22,'acdc31422@gmail.com','ANGIE DANIELA CASALLAS CASTILLO','1000734072');
INSERT INTO client (age,email,name,password) VALUES(63,'fcrockfabian@gmail.com','PEDRO ANTONIO CHACON SUAREZ','19430915');
INSERT INTO client (age,email,name,password) VALUES(29,'lau_diaz_85@hotmail.com','JEISSON DAVID MORALES RAMIREZ','1014249200');
INSERT INTO client (age,email,name,password) VALUES(53,'LAURISPATICO@GMAIL.COM','LAURA PATRICIA BASTIDAS ENRIQUEZ','30744193');
INSERT INTO client (age,email,name,password) VALUES(55,'DONETIERNA@GMAIL.COM','DONELCY JUDITH MONTAÑO CANTILLO','30773645');
INSERT INTO client (age,email,name,password) VALUES(39,'CAROIBARTREBOL@GMAIL.COM','CAROL ANDREA IBARRA CABRERA','59311650');
INSERT INTO client (age,email,name,password) VALUES(35,'JAVIERAMOS11@GMAIL.COM','HEBERTH JAVIER RAMOS VANEGAS','1069722563');
INSERT INTO client (age,email,name,password) VALUES(32,'carmonagloria451@hotmail.com','GLORIA PATRICIA CARMONA GARCIA','1102831058');
INSERT INTO client (age,email,name,password) VALUES(23,'DAJUALPA@HOTMAIL.COM','DANIELA ALEXANDRA MARTINEZ PINEDA','1032507469');
INSERT INTO client (age,email,name,password) VALUES(61,'dayanaelenacampo@gmail.com','HORACIO MIGUEL CAMPO ARIZA','18938474');
INSERT INTO client (age,email,name,password) VALUES(25,'derlimarun@gmail.com','LEIDY PAOLA FLOREZ ROJAS','1002595074');
INSERT INTO client (age,email,name,password) VALUES(45,'ingridalexa14@hotmail.com','SILVERIO DE JESUS SANABRIA CEPEDA','79887137');
INSERT INTO client (age,email,name,password) VALUES(29,'jonathan-hes@hormail.com','JONATHAN HENRIQUEZ MEZA','1023926210');
INSERT INTO client (age,email,name,password) VALUES(49,'delacruzbrenda48@gmail.com','EBER JACINTO CAICEDO ','5366197');
INSERT INTO client (age,email,name,password) VALUES(45,'luisafernandacalderon1978@gmail.com','LUISA FERNANDA CALDERON ','1113039402');
INSERT INTO client (age,email,name,password) VALUES(33,'henrycarvajal96@gmail.com','HENRY ALBERTO CARVAJAL VALBUENA','1115186348');
INSERT INTO client (age,email,name,password) VALUES(32,'YOJANABARBOSA2912@GMAIL.COM','LILIA YOJANNA BARBOSA PICO','1121874401');
INSERT INTO client (age,email,name,password) VALUES(29,'matranetru@enayu.com','ANGEL DEJESUS GARCIA CASTILLO','1125351122');
INSERT INTO client (age,email,name,password) VALUES(31,'RANDYDCUELLO@GMAIL.COM','RANDY DARIEL DUEÑEZ CUELLO','1126706132');
INSERT INTO client (age,email,name,password) VALUES(67,'randydcuello@gmail.com','FOLGUER DUEÑEZ FAJARDO','91150852');
INSERT INTO client (age,email,name,password) VALUES(34,'wildonavila11@outlook.es','WILDON ALBEIRO AVILA VILORIA','1127591993');
INSERT INTO client (age,email,name,password) VALUES(40,'mertofolmo@enayu.com','JOSE DE LOS ANGELES SANDOVAL CONRADO','1129527055');
INSERT INTO client (age,email,name,password) VALUES(37,'JHONFVC1712@GMAIL.COM','JOHN FREDDY VIRGUEZ CERON','1130648180');
INSERT INTO client (age,email,name,password) VALUES(34,'mafergie19_@hotmail.com','MARIA FERNANDA CASTELLANOS QUILINDO','1130680328');
INSERT INTO client (age,email,name,password) VALUES(59,'rzo97893@zzrgg.com','LUIS CARLOS RODRIGUEZ ','11341218');
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 1',1,1);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 2',2,2);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 3',3,3);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 4',4,4);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 5',5,5);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 6',6,6);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 7',7,7);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 8',8,8);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 9',9,9);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 10',10,10);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 11',11,1);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 12',12,2);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 13',13,3);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 14',14,4);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 15',15,5);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 16',16,6);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 17',17,7);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 18',18,8);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 19',19,9);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 20',20,10);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 21',21,1);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 22',22,2);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 23',23,3);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 24',24,4);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 25',25,5);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 26',26,6);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 27',27,7);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 28',28,8);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 29',29,9);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 30',30,10);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 31',31,1);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 32',32,2);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 33',33,3);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 34',34,4);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 35',35,5);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 36',36,6);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 37',37,7);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 38',38,8);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 39',39,9);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 40',40,10);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 41',41,1);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 42',42,2);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 43',43,3);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 44',44,4);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 45',45,5);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 46',46,6);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 47',47,7);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 48',48,8);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 49',49,9);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 50',50,10);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 51',1,1);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 52',2,2);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 53',3,3);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 54',4,4);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 55',5,5);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 56',6,6);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 57',7,7);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 58',8,8);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 59',9,9);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 60',10,10);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 61',11,1);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 62',12,2);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 63',13,3);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 64',14,4);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 65',15,5);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 66',16,6);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 67',17,7);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 68',18,8);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 69',19,9);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 70',20,10);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 71',21,1);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 72',22,2);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 73',23,3);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 74',24,4);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 75',25,5);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 76',26,6);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 77',27,7);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 78',28,8);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 79',29,9);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 80',30,10);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 81',31,1);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 82',32,2);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 83',33,3);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 84',34,4);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 85',35,5);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 86',36,6);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 87',37,7);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 88',38,8);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 89',39,9);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 90',40,10);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 91',41,1);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 92',42,2);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 93',43,3);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 94',44,4);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 95',45,5);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 96',46,6);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 97',47,7);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 98',48,8);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 99',49,9);
INSERT INTO message (message_text,client_id,farm_id) VALUES('Mensaje 100',50,10);
INSERT INTO reservation(devolution_date,start_date,status,client_id,farm_id) VALUES(STR_TO_DATE('01-10-2022', '%d-%m-%Y'),STR_TO_DATE('05-01-2022', '%d-%m-%Y'),'created',1,1);
INSERT INTO reservation(devolution_date,start_date,status,client_id,farm_id) VALUES(STR_TO_DATE('01-10-2022', '%d-%m-%Y'),STR_TO_DATE('05-01-2022', '%d-%m-%Y'),'created',2,2);
INSERT INTO reservation(devolution_date,start_date,status,client_id,farm_id) VALUES(STR_TO_DATE('01-10-2022', '%d-%m-%Y'),STR_TO_DATE('05-01-2022', '%d-%m-%Y'),'created',3,3);
INSERT INTO reservation(devolution_date,start_date,status,client_id,farm_id) VALUES(STR_TO_DATE('01-10-2022', '%d-%m-%Y'),STR_TO_DATE('05-01-2022', '%d-%m-%Y'),'created',4,5);
INSERT INTO reservation(devolution_date,start_date,status,client_id,farm_id) VALUES(STR_TO_DATE('01-10-2022', '%d-%m-%Y'),STR_TO_DATE('05-01-2022', '%d-%m-%Y'),'created',5,5);
INSERT INTO reservation(devolution_date,start_date,status,client_id,farm_id) VALUES(STR_TO_DATE('01-10-2022', '%d-%m-%Y'),STR_TO_DATE('05-01-2022', '%d-%m-%Y'),'created',6,6);
INSERT INTO reservation(devolution_date,start_date,status,client_id,farm_id) VALUES(STR_TO_DATE('01-10-2022', '%d-%m-%Y'),STR_TO_DATE('05-01-2022', '%d-%m-%Y'),'created',7,7);
INSERT INTO reservation(devolution_date,start_date,status,client_id,farm_id) VALUES(STR_TO_DATE('01-10-2022', '%d-%m-%Y'),STR_TO_DATE('05-01-2022', '%d-%m-%Y'),'created',8,8);
INSERT INTO reservation(devolution_date,start_date,status,client_id,farm_id) VALUES(STR_TO_DATE('01-10-2022', '%d-%m-%Y'),STR_TO_DATE('05-01-2022', '%d-%m-%Y'),'created',9,9);
INSERT INTO reservation(devolution_date,start_date,status,client_id,farm_id) VALUES(STR_TO_DATE('01-10-2022', '%d-%m-%Y'),STR_TO_DATE('05-01-2022', '%d-%m-%Y'),'created',10,10);